import { Payment, Booking } from "@shared/schema";

export enum PaymentStatus {
  Pending = 'pending',
  Processing = 'processing',
  Completed = 'completed',
  Failed = 'failed',
  Refunded = 'refunded',
  Cancelled = 'cancelled',
  Expired = 'expired',
  ManualReviewRequired = 'manual_review_required',
}

export interface PaymentInitiationRequest {
  bookingId: string;
  amount: number; // in smallest currency unit, e.g., cents
  currency: string;
  successUrl: string;
  cancelUrl: string;
  customerEmail?: string;
  customerName?: string;
  metadata?: Record<string, any>; // Gateway-specific metadata
}

export interface PaymentInitiationResponse {
  success: boolean;
  message?: string;
  redirectUrl?: string; // URL to redirect the user to complete payment
  transactionId?: string; // Internal transaction ID generated by the gateway
  paymentId?: string; // Our internal payment ID
  amount?: number;
  currency?: string;
  provider?: string;
  failureReason?: string;
}

export interface PaymentStatusRequest {
  paymentId: string; // Our internal payment ID
  gatewayReference?: string; // Reference from the payment gateway
}

export interface PaymentStatusResponse {
  status: PaymentStatus;
  gatewayReference?: string; // External reference from bank/gateway
  amount?: number;
  currency?: string;
  message?: string; // Any status message from the gateway
  failureReason?: string; // Standardized failure reason
}

export interface WebhookEvent {
  gatewaySlug: string; 
  rawEvent: any; 
  signature?: string; 
  headers?: Record<string, string>; 
}

export interface WebhookResponse {
  success: boolean;
  message?: string;
  paymentId?: string; 
  bookingId?: string; 
  newPaymentStatus?: PaymentStatus;
  gatewayReference?: string;
  failureReason?: string;
}

export interface PaymentGatewayService {
  initiatePayment(request: PaymentInitiationRequest): Promise<PaymentInitiationResponse>;
  handleWebhook(event: WebhookEvent): Promise<WebhookResponse>;
  queryPaymentStatus(request: PaymentStatusRequest): Promise<PaymentStatusResponse>;
  refundPayment?(payment: Payment, amount?: number, reason?: string): Promise<PaymentStatusResponse>;
}
export interface HostedBankGatewayAdapter extends PaymentGatewayService {
  readonly providerSlug: 'anz' | 'bsp' | 'bred';

  /**
   * Creates a hosted checkout session and returns a redirect URL.
   * MUST NOT capture funds synchronously.
   */
  initiatePayment(
    request: PaymentInitiationRequest
  ): Promise<PaymentInitiationResponse & { 
    success: boolean;
    redirectUrl?: string;
    gatewayReference?: string;
  }>;

  /**
   * Processes return redirects or server-to-server callbacks.
   * MUST normalize into internal WebhookEvent shape.
   */
  handleWebhook(
    event: WebhookEvent
  ): Promise<WebhookResponse & {
    normalizedStatus?: 'completed' | 'failed' | 'cancelled' | 'expired';
    gatewayReference?: string;
    failureReason?: string;
  }>;

  /**
   * Queries the bank for authoritative status.
   * Used by Phase 4 reconciliation worker.
   */
  queryPaymentStatus(
    request: PaymentStatusRequest
  ): Promise<PaymentStatusResponse>;
}
